name = "GridGraphs"
uuid = "dd2b58c7-5af7-4f17-9e46-57c68ac813fb"
authors = ["Guillaume Dalle <22795598+gdalle@users.noreply.github.com> and contributors"]
version = "0.8.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataStructures = "0.18.12"
Graphs = "1.6"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
